name: Build and Release to S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CLIENT_ID  : ${{ secrets.GOOGLE_CLIENT_ID }}
  TEST_CLOUD_FLARE_ID  : ${{ secrets.TEST_CLOUD_FLARE_ID }}
  PROD_CLOUD_FLARE_ID  : ${{ secrets.PROD_CLOUD_FLARE_ID }}
  TEST_BACKEND_URL  : ${{ secrets.TEST_BACKEND_URL }}
  PROD_BACKEND_URL  : ${{ secrets.PROD_BACKEND_URL }}
  TEST_S3_BUCKET_NAME : ${{ secrets.TEST_S3_BUCKET_NAME }}
  PROD_S3_BUCKET_NAME : ${{ secrets.PROD_S3_BUCKET_NAME }}
jobs:
  build-and-deploy-to-test-env:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for test
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build React App and deploy to S3
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ env.GOOGLE_CLIENT_ID }}
          VITE_CLOUD_FLARE_ID: ${{ env.TEST_CLOUD_FLARE_ID }}
          VITE_BACKEND_URL: ${{ env.TEST_BACKEND_URL }}
        run: |
          npm install
          npm run build
          ls -la ./build  # List contents of the build directory
          aws s3 sync ./build s3://${{ env.TEST_S3_BUCKET_NAME }} --delete

  build-and-deploy-to-prod-env:
    runs-on: ubuntu-latest
    needs: build-and-deploy-to-test-env
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for production
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build React App and upload to S3
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ env.GOOGLE_CLIENT_ID }}
          VITE_CLOUD_FLARE_ID: ${{ env.PROD_CLOUD_FLARE_ID }}
          VITE_BACKEND_URL: ${{ env.PROD_BACKEND_URL }}
        run: |
          npm install
          npm run build
          aws s3 sync ./build s3://${{ env.PROD_S3_BUCKET_NAME }} --delete