name: Terraform Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TEST_WEBSITE_URL : ${{ secrets.WEBSITE_URL_TEST }}
  TEST_S3_BUCKET_NAME : ${{ secrets.TEST_S3_BUCKET_NAME }}
  PROD_WEBSITE_URL : ${{ secrets.WEBSITE_URL_PROD }}
  PROD_S3_BUCKET_NAME : ${{ secrets.PROD_S3_BUCKET_NAME }}

jobs:
  terraform-test-env:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for test
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init (Test)
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan (Test)
        env:
          TF_VAR_environment: "test"
          TF_VAR_website_url: ${{ env.TEST_WEBSITE_URL }}
          TF_VAR_s3_bucket_name: ${{ env.TEST_S3_BUCKET_NAME }}
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply to Test
        env:
          TF_VAR_environment: "test"
          TF_VAR_website_url: ${{ env.TEST_WEBSITE_URL }}
          TF_VAR_s3_bucket_name: ${{ env.TEST_S3_BUCKET_NAME }}
        run: terraform apply -auto-approve
        working-directory: ./terraform

  terraform-prod-env:
    runs-on: ubuntu-latest
    needs: terraform-test-env
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for production
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init (Production)
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan (Production)
        env:
          TF_VAR_environment: "production"
          TF_VAR_website_url: ${{ env.PROD_WEBSITE_URL }}
          TF_VAR_s3_bucket_name: ${{ env.PROD_S3_BUCKET_NAME }}
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply to Production
        env:
          TF_VAR_environment: "production"
          TF_VAR_website_url: ${{ env.PROD_WEBSITE_URL }}
          TF_VAR_s3_bucket_name: ${{ env.PROD_S3_BUCKET_NAME }}
        run: terraform apply -auto-approve
        working-directory: ./terraform